/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CeteSavaslariRouteImport } from './routes/cete-savaslari'
import { Route as OynaSlugRouteImport } from './routes/oyna.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CeteSavaslariRoute = CeteSavaslariRouteImport.update({
  id: '/cete-savaslari',
  path: '/cete-savaslari',
  getParentRoute: () => rootRouteImport,
} as any)
const OynaSlugRoute = OynaSlugRouteImport.update({
  id: '/oyna/$slug',
  path: '/oyna/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cete-savaslari': typeof CeteSavaslariRoute
  '/oyna/$slug': typeof OynaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cete-savaslari': typeof CeteSavaslariRoute
  '/oyna/$slug': typeof OynaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cete-savaslari': typeof CeteSavaslariRoute
  '/oyna/$slug': typeof OynaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reset-password' | '/auth/callback' | '/cete-savaslari' | '/oyna/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reset-password' | '/auth/callback' | '/cete-savaslari' | '/oyna/$slug'
  id: '__root__' | '/' | '/reset-password' | '/auth/callback' | '/cete-savaslari' | '/oyna/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CeteSavaslariRoute: typeof CeteSavaslariRoute
  OynaSlugRoute: typeof OynaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cete-savaslari': {
      id: '/cete-savaslari'
      path: '/cete-savaslari'
      fullPath: '/cete-savaslari'
      preLoaderRoute: typeof CeteSavaslariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyna/$slug': {
      id: '/oyna/$slug'
      path: '/oyna/$slug'
      fullPath: '/oyna/$slug'
      preLoaderRoute: typeof OynaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CeteSavaslariRoute: CeteSavaslariRoute,
  OynaSlugRoute: OynaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
